### ISSUE TITLE
skin issues

### ISSUE THREAD

**Issue by xh-hnu** [Spikeysanju/Wiggles#8]
Could you share the skin of the simulator?

**Comment by Spikeysanju** [comment]
I didn't understand. Can you please elaborate more?

**Comment by xh-hnu** [comment]
Your Android emulator looks like an iPhone. How do you set it up？

**Comment by Spikeysanju** [comment]
Nope I took screenshot & added iPhone mock separately with Figma 😃 . Closing this issue. Have a great day!
